<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
 public function run(): void
    {
        $rows = [
            ['code' => 'AF', 'country_ar' => 'أفغانستان', 'country_en' => 'Afghanistan', 'nationality_ar' => 'أفغاني', 'nationality_en' => 'Afghan', 'preferred_language' => 'fa'],
            ['code' => 'AL', 'country_ar' => 'ألبانيا', 'country_en' => 'Albania', 'nationality_ar' => 'ألباني', 'nationality_en' => 'Albanian', 'preferred_language' => 'sq'],
            ['code' => 'DZ', 'country_ar' => 'الجزائر', 'country_en' => 'Algeria', 'nationality_ar' => 'جزائري', 'nationality_en' => 'Algerian', 'preferred_language' => 'ar'],
            ['code' => 'AD', 'country_ar' => 'أندورا', 'country_en' => 'Andorra', 'nationality_ar' => 'أندوري', 'nationality_en' => 'Andorran', 'preferred_language' => 'ca'],
            ['code' => 'AO', 'country_ar' => 'أنغولا', 'country_en' => 'Angola', 'nationality_ar' => 'أنغولي', 'nationality_en' => 'Angolan', 'preferred_language' => 'pt'],
            ['code' => 'AG', 'country_ar' => 'أنتيغوا وباربودا', 'country_en' => 'Antigua and Barbuda', 'nationality_ar' => 'أنتيغوي وباربودي', 'nationality_en' => 'Antiguan and Barbudan', 'preferred_language' => 'en'],
            ['code' => 'AR', 'country_ar' => 'الأرجنتين', 'country_en' => 'Argentina', 'nationality_ar' => 'أرجنتيني', 'nationality_en' => 'Argentine', 'preferred_language' => 'es'],
            ['code' => 'AM', 'country_ar' => 'أرمينيا', 'country_en' => 'Armenia', 'nationality_ar' => 'أرميني', 'nationality_en' => 'Armenian', 'preferred_language' => 'hy'],
            ['code' => 'AU', 'country_ar' => 'أستراليا', 'country_en' => 'Australia', 'nationality_ar' => 'أسترالي', 'nationality_en' => 'Australian', 'preferred_language' => 'en'],
            ['code' => 'AT', 'country_ar' => 'النمسا', 'country_en' => 'Austria', 'nationality_ar' => 'نمساوي', 'nationality_en' => 'Austrian', 'preferred_language' => 'de'],
            ['code' => 'AZ', 'country_ar' => 'أذربيجان', 'country_en' => 'Azerbaijan', 'nationality_ar' => 'أذربيجاني', 'nationality_en' => 'Azerbaijani', 'preferred_language' => 'az'],
            ['code' => 'BS', 'country_ar' => 'جزر البهاما', 'country_en' => 'Bahamas', 'nationality_ar' => 'باهامي', 'nationality_en' => 'Bahamian', 'preferred_language' => 'en'],
            ['code' => 'BH', 'country_ar' => 'البحرين', 'country_en' => 'Bahrain', 'nationality_ar' => 'بحريني', 'nationality_en' => 'Bahraini', 'preferred_language' => 'ar'],
            ['code' => 'BD', 'country_ar' => 'بنغلاديش', 'country_en' => 'Bangladesh', 'nationality_ar' => 'بنغلاديشي', 'nationality_en' => 'Bangladeshi', 'preferred_language' => 'bn'],
            ['code' => 'BB', 'country_ar' => 'بربادوس', 'country_en' => 'Barbados', 'nationality_ar' => 'بربادوسي', 'nationality_en' => 'Barbadian', 'preferred_language' => 'en'],
            ['code' => 'BY', 'country_ar' => 'بيلاروس', 'country_en' => 'Belarus', 'nationality_ar' => 'بيلاروسي', 'nationality_en' => 'Belarusian', 'preferred_language' => 'be'],
            ['code' => 'BE', 'country_ar' => 'بلجيكا', 'country_en' => 'Belgium', 'nationality_ar' => 'بلجيكي', 'nationality_en' => 'Belgian', 'preferred_language' => 'nl'],
            ['code' => 'BZ', 'country_ar' => 'بليز', 'country_en' => 'Belize', 'nationality_ar' => 'بليزي', 'nationality_en' => 'Belizean', 'preferred_language' => 'en'],
            ['code' => 'BJ', 'country_ar' => 'بنين', 'country_en' => 'Benin', 'nationality_ar' => 'بنيني', 'nationality_en' => 'Beninese', 'preferred_language' => 'fr'],
            ['code' => 'BT', 'country_ar' => 'بوتان', 'country_en' => 'Bhutan', 'nationality_ar' => 'بوتاني', 'nationality_en' => 'Bhutanese', 'preferred_language' => 'dz'],
            ['code' => 'BO', 'country_ar' => 'بوليفيا', 'country_en' => 'Bolivia', 'nationality_ar' => 'بوليفي', 'nationality_en' => 'Bolivian', 'preferred_language' => 'es'],
            ['code' => 'BA', 'country_ar' => 'البوسنة والهرسك', 'country_en' => 'Bosnia and Herzegovina', 'nationality_ar' => 'بوسني', 'nationality_en' => 'Bosnian and Herzegovinian', 'preferred_language' => 'bs'],
            ['code' => 'BW', 'country_ar' => 'بوتسوانا', 'country_en' => 'Botswana', 'nationality_ar' => 'بوتسواني', 'nationality_en' => 'Motswana', 'preferred_language' => 'en'],
            ['code' => 'BR', 'country_ar' => 'البرازيل', 'country_en' => 'Brazil', 'nationality_ar' => 'برازيلي', 'nationality_en' => 'Brazilian', 'preferred_language' => 'pt'],
            ['code' => 'BN', 'country_ar' => 'بروناي', 'country_en' => 'Brunei', 'nationality_ar' => 'بروناوي', 'nationality_en' => 'Bruneian', 'preferred_language' => 'ms'],
            ['code' => 'BG', 'country_ar' => 'بلغاريا', 'country_en' => 'Bulgaria', 'nationality_ar' => 'بلغاري', 'nationality_en' => 'Bulgarian', 'preferred_language' => 'bg'],
            ['code' => 'BF', 'country_ar' => 'بوركينا فاسو', 'country_en' => 'Burkina Faso', 'nationality_ar' => 'بوركيني', 'nationality_en' => 'Burkinabe', 'preferred_language' => 'fr'],
            ['code' => 'BI', 'country_ar' => 'بوروندي', 'country_en' => 'Burundi', 'nationality_ar' => 'بوروندي', 'nationality_en' => 'Burundian', 'preferred_language' => 'rn'],
            ['code' => 'CV', 'country_ar' => 'الرأس الأخضر', 'country_en' => 'Cabo Verde', 'nationality_ar' => 'رأسي أخضري', 'nationality_en' => 'Cabo Verdean', 'preferred_language' => 'pt'],
            ['code' => 'KH', 'country_ar' => 'كمبوديا', 'country_en' => 'Cambodia', 'nationality_ar' => 'كمبودي', 'nationality_en' => 'Cambodian', 'preferred_language' => 'km'],
            ['code' => 'CM', 'country_ar' => 'الكاميرون', 'country_en' => 'Cameroon', 'nationality_ar' => 'كاميروني', 'nationality_en' => 'Cameroonian', 'preferred_language' => 'fr'],
            ['code' => 'CA', 'country_ar' => 'كندا', 'country_en' => 'Canada', 'nationality_ar' => 'كندي', 'nationality_en' => 'Canadian', 'preferred_language' => 'en'],
            ['code' => 'CF', 'country_ar' => 'جمهورية أفريقيا الوسطى', 'country_en' => 'Central African Republic', 'nationality_ar' => 'أفريقي أوسطي', 'nationality_en' => 'Central African', 'preferred_language' => 'fr'],
            ['code' => 'TD', 'country_ar' => 'تشاد', 'country_en' => 'Chad', 'nationality_ar' => 'تشادي', 'nationality_en' => 'Chadian', 'preferred_language' => 'fr'],
            ['code' => 'CL', 'country_ar' => 'تشيلي', 'country_en' => 'Chile', 'nationality_ar' => 'تشيلي', 'nationality_en' => 'Chilean', 'preferred_language' => 'es'],
            ['code' => 'CN', 'country_ar' => 'الصين', 'country_en' => 'China', 'nationality_ar' => 'صيني', 'nationality_en' => 'Chinese', 'preferred_language' => 'zh'],
            ['code' => 'CO', 'country_ar' => 'كولومبيا', 'country_en' => 'Colombia', 'nationality_ar' => 'كولومبي', 'nationality_en' => 'Colombian', 'preferred_language' => 'es'],
            ['code' => 'KM', 'country_ar' => 'جزر القمر', 'country_en' => 'Comoros', 'nationality_ar' => 'قمري', 'nationality_en' => 'Comorian', 'preferred_language' => 'ar'],
            ['code' => 'CG', 'country_ar' => 'الكونغو', 'country_en' => 'Congo', 'nationality_ar' => 'كونغولي', 'nationality_en' => 'Congolese', 'preferred_language' => 'fr'],
            ['code' => 'CR', 'country_ar' => 'كوستاريكا', 'country_en' => 'Costa Rica', 'nationality_ar' => 'كوستاريكي', 'nationality_en' => 'Costa Rican', 'preferred_language' => 'es'],
            ['code' => 'CI', 'country_ar' => 'كوت ديفوار', 'country_en' => 'Côte d\'Ivoire', 'nationality_ar' => 'إيفواري', 'nationality_en' => 'Ivorian', 'preferred_language' => 'fr'],
            ['code' => 'HR', 'country_ar' => 'كرواتيا', 'country_en' => 'Croatia', 'nationality_ar' => 'كرواتي', 'nationality_en' => 'Croatian', 'preferred_language' => 'hr'],
            ['code' => 'CU', 'country_ar' => 'كوبا', 'country_en' => 'Cuba', 'nationality_ar' => 'كوبي', 'nationality_en' => 'Cuban', 'preferred_language' => 'es'],
            ['code' => 'CY', 'country_ar' => 'قبرص', 'country_en' => 'Cyprus', 'nationality_ar' => 'قبرصي', 'nationality_en' => 'Cypriot', 'preferred_language' => 'el'],
            ['code' => 'CZ', 'country_ar' => 'التشيك', 'country_en' => 'Czechia', 'nationality_ar' => 'تشيكي', 'nationality_en' => 'Czech', 'preferred_language' => 'cs'],
            ['code' => 'CD', 'country_ar' => 'جمهورية الكونغو الديمقراطية', 'country_en' => 'Democratic Republic of the Congo', 'nationality_ar' => 'كونغولي ديمقراطي', 'nationality_en' => 'Congolese', 'preferred_language' => 'fr'],
            ['code' => 'DK', 'country_ar' => 'الدنمارك', 'country_en' => 'Denmark', 'nationality_ar' => 'دنماركي', 'nationality_en' => 'Danish', 'preferred_language' => 'da'],
            ['code' => 'DJ', 'country_ar' => 'جيبوتي', 'country_en' => 'Djibouti', 'nationality_ar' => 'جيبوتي', 'nationality_en' => 'Djiboutian', 'preferred_language' => 'ar'],
            ['code' => 'DM', 'country_ar' => 'دومينيكا', 'country_en' => 'Dominica', 'nationality_ar' => 'دومينيكي', 'nationality_en' => 'Dominican', 'preferred_language' => 'en'],
            ['code' => 'DO', 'country_ar' => 'جمهورية الدومينيكان', 'country_en' => 'Dominican Republic', 'nationality_ar' => 'دومينيكاني', 'nationality_en' => 'Dominican', 'preferred_language' => 'es'],
            ['code' => 'EC', 'country_ar' => 'الإكوادور', 'country_en' => 'Ecuador', 'nationality_ar' => 'إكوادوري', 'nationality_en' => 'Ecuadorian', 'preferred_language' => 'es'],
            ['code' => 'EG', 'country_ar' => 'مصر', 'country_en' => 'Egypt', 'nationality_ar' => 'مصري', 'nationality_en' => 'Egyptian', 'preferred_language' => 'ar'],
            ['code' => 'SV', 'country_ar' => 'السلفادور', 'country_en' => 'El Salvador', 'nationality_ar' => 'سلفادوري', 'nationality_en' => 'Salvadoran', 'preferred_language' => 'es'],
            ['code' => 'GQ', 'country_ar' => 'غينيا الاستوائية', 'country_en' => 'Equatorial Guinea', 'nationality_ar' => 'غيني استوائي', 'nationality_en' => 'Equatoguinean', 'preferred_language' => 'es'],
            ['code' => 'ER', 'country_ar' => 'إريتريا', 'country_en' => 'Eritrea', 'nationality_ar' => 'إريتري', 'nationality_en' => 'Eritrean', 'preferred_language' => 'ti'],
            ['code' => 'EE', 'country_ar' => 'إستونيا', 'country_en' => 'Estonia', 'nationality_ar' => 'إستوني', 'nationality_en' => 'Estonian', 'preferred_language' => 'et'],
            ['code' => 'SZ', 'country_ar' => 'إسواتيني', 'country_en' => 'Eswatini', 'nationality_ar' => 'إسواتيني', 'nationality_en' => 'Swazi', 'preferred_language' => 'en'],
            ['code' => 'ET', 'country_ar' => 'إثيوبيا', 'country_en' => 'Ethiopia', 'nationality_ar' => 'إثيوبي', 'nationality_en' => 'Ethiopian', 'preferred_language' => 'am'],
            ['code' => 'FJ', 'country_ar' => 'فيجي', 'country_en' => 'Fiji', 'nationality_ar' => 'فيجي', 'nationality_en' => 'Fijian', 'preferred_language' => 'en'],
            ['code' => 'FI', 'country_ar' => 'فنلندا', 'country_en' => 'Finland', 'nationality_ar' => 'فنلندي', 'nationality_en' => 'Finnish', 'preferred_language' => 'fi'],
            ['code' => 'FR', 'country_ar' => 'فرنسا', 'country_en' => 'France', 'nationality_ar' => 'فرنسي', 'nationality_en' => 'French', 'preferred_language' => 'fr'],
            ['code' => 'GA', 'country_ar' => 'الغابون', 'country_en' => 'Gabon', 'nationality_ar' => 'غابوني', 'nationality_en' => 'Gabonese', 'preferred_language' => 'fr'],
            ['code' => 'GM', 'country_ar' => 'غامبيا', 'country_en' => 'Gambia', 'nationality_ar' => 'غامبي', 'nationality_en' => 'Gambian', 'preferred_language' => 'en'],
            ['code' => 'GE', 'country_ar' => 'جورجيا', 'country_en' => 'Georgia', 'nationality_ar' => 'جورجي', 'nationality_en' => 'Georgian', 'preferred_language' => 'ka'],
            ['code' => 'DE', 'country_ar' => 'ألمانيا', 'country_en' => 'Germany', 'nationality_ar' => 'ألماني', 'nationality_en' => 'German', 'preferred_language' => 'de'],
            ['code' => 'GH', 'country_ar' => 'غانا', 'country_en' => 'Ghana', 'nationality_ar' => 'غاني', 'nationality_en' => 'Ghanaian', 'preferred_language' => 'en'],
            ['code' => 'GR', 'country_ar' => 'اليونان', 'country_en' => 'Greece', 'nationality_ar' => 'يوناني', 'nationality_en' => 'Greek', 'preferred_language' => 'el'],
            ['code' => 'GD', 'country_ar' => 'غرينادا', 'country_en' => 'Grenada', 'nationality_ar' => 'غرينادي', 'nationality_en' => 'Grenadian', 'preferred_language' => 'en'],
            ['code' => 'GT', 'country_ar' => 'غواتيمالا', 'country_en' => 'Guatemala', 'nationality_ar' => 'غواتيمالي', 'nationality_en' => 'Guatemalan', 'preferred_language' => 'es'],
            ['code' => 'GN', 'country_ar' => 'غينيا', 'country_en' => 'Guinea', 'nationality_ar' => 'غيني', 'nationality_en' => 'Guinean', 'preferred_language' => 'fr'],
            ['code' => 'GW', 'country_ar' => 'غينيا بيساو', 'country_en' => 'Guinea-Bissau', 'nationality_ar' => 'غيني بيساوي', 'nationality_en' => 'Bissau-Guinean', 'preferred_language' => 'pt'],
            ['code' => 'GY', 'country_ar' => 'غيانا', 'country_en' => 'Guyana', 'nationality_ar' => 'غياني', 'nationality_en' => 'Guyanese', 'preferred_language' => 'en'],
            ['code' => 'HT', 'country_ar' => 'هايتي', 'country_en' => 'Haiti', 'nationality_ar' => 'هايتي', 'nationality_en' => 'Haitian', 'preferred_language' => 'fr'],
            ['code' => 'HN', 'country_ar' => 'هندوراس', 'country_en' => 'Honduras', 'nationality_ar' => 'هندوراسي', 'nationality_en' => 'Honduran', 'preferred_language' => 'es'],
            ['code' => 'HU', 'country_ar' => 'المجر', 'country_en' => 'Hungary', 'nationality_ar' => 'مجري', 'nationality_en' => 'Hungarian', 'preferred_language' => 'hu'],
            ['code' => 'IS', 'country_ar' => 'آيسلندا', 'country_en' => 'Iceland', 'nationality_ar' => 'آيسلندي', 'nationality_en' => 'Icelandic', 'preferred_language' => 'is'],
            ['code' => 'IN', 'country_ar' => 'الهند', 'country_en' => 'India', 'nationality_ar' => 'هندي', 'nationality_en' => 'Indian', 'preferred_language' => 'hi'],
            ['code' => 'ID', 'country_ar' => 'إندونيسيا', 'country_en' => 'Indonesia', 'nationality_ar' => 'إندونيسي', 'nationality_en' => 'Indonesian', 'preferred_language' => 'id'],
            ['code' => 'IR', 'country_ar' => 'إيران', 'country_en' => 'Iran', 'nationality_ar' => 'إيراني', 'nationality_en' => 'Iranian', 'preferred_language' => 'fa'],
            ['code' => 'IQ', 'country_ar' => 'العراق', 'country_en' => 'Iraq', 'nationality_ar' => 'عراقي', 'nationality_en' => 'Iraqi', 'preferred_language' => 'ar'],
            ['code' => 'IE', 'country_ar' => 'أيرلندا', 'country_en' => 'Ireland', 'nationality_ar' => 'أيرلندي', 'nationality_en' => 'Irish', 'preferred_language' => 'en'],
            ['code' => 'IL', 'country_ar' => 'إسرائيل', 'country_en' => 'Israel', 'nationality_ar' => 'إسرائيلي', 'nationality_en' => 'Israeli', 'preferred_language' => 'he'],
            ['code' => 'IT', 'country_ar' => 'إيطاليا', 'country_en' => 'Italy', 'nationality_ar' => 'إيطالي', 'nationality_en' => 'Italian', 'preferred_language' => 'it'],
            ['code' => 'JM', 'country_ar' => 'جامايكا', 'country_en' => 'Jamaica', 'nationality_ar' => 'جامايكي', 'nationality_en' => 'Jamaican', 'preferred_language' => 'en'],
            ['code' => 'JP', 'country_ar' => 'اليابان', 'country_en' => 'Japan', 'nationality_ar' => 'ياباني', 'nationality_en' => 'Japanese', 'preferred_language' => 'ja'],
            ['code' => 'JO', 'country_ar' => 'الأردن', 'country_en' => 'Jordan', 'nationality_ar' => 'أردني', 'nationality_en' => 'Jordanian', 'preferred_language' => 'ar'],
            ['code' => 'KZ', 'country_ar' => 'كازاخستان', 'country_en' => 'Kazakhstan', 'nationality_ar' => 'كازاخستاني', 'nationality_en' => 'Kazakhstani', 'preferred_language' => 'kk'],
            ['code' => 'KE', 'country_ar' => 'كينيا', 'country_en' => 'Kenya', 'nationality_ar' => 'كيني', 'nationality_en' => 'Kenyan', 'preferred_language' => 'sw'],
            ['code' => 'KI', 'country_ar' => 'كيريباتي', 'country_en' => 'Kiribati', 'nationality_ar' => 'كيريباتي', 'nationality_en' => 'I-Kiribati', 'preferred_language' => 'en'],
            ['code' => 'KW', 'country_ar' => 'الكويت', 'country_en' => 'Kuwait', 'nationality_ar' => 'كويتي', 'nationality_en' => 'Kuwaiti', 'preferred_language' => 'ar'],
            ['code' => 'KG', 'country_ar' => 'قيرغيزستان', 'country_en' => 'Kyrgyzstan', 'nationality_ar' => 'قيرغيزستاني', 'nationality_en' => 'Kyrgyzstani', 'preferred_language' => 'ky'],
            ['code' => 'LA', 'country_ar' => 'لاوس', 'country_en' => 'Laos', 'nationality_ar' => 'لاوسي', 'nationality_en' => 'Lao', 'preferred_language' => 'lo'],
            ['code' => 'LV', 'country_ar' => 'لاتفيا', 'country_en' => 'Latvia', 'nationality_ar' => 'لاتفي', 'nationality_en' => 'Latvian', 'preferred_language' => 'lv'],
            ['code' => 'LB', 'country_ar' => 'لبنان', 'country_en' => 'Lebanon', 'nationality_ar' => 'لبناني', 'nationality_en' => 'Lebanese', 'preferred_language' => 'ar'],
            ['code' => 'LS', 'country_ar' => 'ليسوتو', 'country_en' => 'Lesotho', 'nationality_ar' => 'ليسوتي', 'nationality_en' => 'Basotho', 'preferred_language' => 'en'],
            ['code' => 'LR', 'country_ar' => 'ليبيريا', 'country_en' => 'Liberia', 'nationality_ar' => 'ليبيري', 'nationality_en' => 'Liberian', 'preferred_language' => 'en'],
            ['code' => 'LY', 'country_ar' => 'ليبيا', 'country_en' => 'Libya', 'nationality_ar' => 'ليبي', 'nationality_en' => 'Libyan', 'preferred_language' => 'ar'],
            ['code' => 'LI', 'country_ar' => 'ليختنشتاين', 'country_en' => 'Liechtenstein', 'nationality_ar' => 'ليختنشتايني', 'nationality_en' => 'Liechtensteiner', 'preferred_language' => 'de'],
            ['code' => 'LT', 'country_ar' => 'ليتوانيا', 'country_en' => 'Lithuania', 'nationality_ar' => 'ليتواني', 'nationality_en' => 'Lithuanian', 'preferred_language' => 'lt'],
            ['code' => 'LU', 'country_ar' => 'لوكسمبورغ', 'country_en' => 'Luxembourg', 'nationality_ar' => 'لوكسمبورغي', 'nationality_en' => 'Luxembourgish', 'preferred_language' => 'lb'],
            ['code' => 'MG', 'country_ar' => 'مدغشقر', 'country_en' => 'Madagascar', 'nationality_ar' => 'مدغشقري', 'nationality_en' => 'Malagasy', 'preferred_language' => 'mg'],
            ['code' => 'MW', 'country_ar' => 'مالاوي', 'country_en' => 'Malawi', 'nationality_ar' => 'مالاوي', 'nationality_en' => 'Malawian', 'preferred_language' => 'en'],
            ['code' => 'MY', 'country_ar' => 'ماليزيا', 'country_en' => 'Malaysia', 'nationality_ar' => 'ماليزي', 'nationality_en' => 'Malaysian', 'preferred_language' => 'ms'],
            ['code' => 'MV', 'country_ar' => 'المالديف', 'country_en' => 'Maldives', 'nationality_ar' => 'مالديفي', 'nationality_en' => 'Maldivian', 'preferred_language' => 'dv'],
            ['code' => 'ML', 'country_ar' => 'مالي', 'country_en' => 'Mali', 'nationality_ar' => 'مالي', 'nationality_en' => 'Malian', 'preferred_language' => 'fr'],
            ['code' => 'MT', 'country_ar' => 'مالطا', 'country_en' => 'Malta', 'nationality_ar' => 'مالطي', 'nationality_en' => 'Maltese', 'preferred_language' => 'mt'],
            ['code' => 'MH', 'country_ar' => 'جزر مارشال', 'country_en' => 'Marshall Islands', 'nationality_ar' => 'مارشالي', 'nationality_en' => 'Marshallese', 'preferred_language' => 'en'],
            ['code' => 'MR', 'country_ar' => 'موريتانيا', 'country_en' => 'Mauritania', 'nationality_ar' => 'موريتاني', 'nationality_en' => 'Mauritanian', 'preferred_language' => 'ar'],
            ['code' => 'MU', 'country_ar' => 'موريشيوس', 'country_en' => 'Mauritius', 'nationality_ar' => 'موريشيوسي', 'nationality_en' => 'Mauritian', 'preferred_language' => 'en'],
            ['code' => 'MX', 'country_ar' => 'المكسيك', 'country_en' => 'Mexico', 'nationality_ar' => 'مكسيكي', 'nationality_en' => 'Mexican', 'preferred_language' => 'es'],
            ['code' => 'FM', 'country_ar' => 'ميكرونيزيا', 'country_en' => 'Micronesia', 'nationality_ar' => 'ميكرونيزي', 'nationality_en' => 'Micronesian', 'preferred_language' => 'en'],
            ['code' => 'MD', 'country_ar' => 'مولدوفا', 'country_en' => 'Moldova', 'nationality_ar' => 'مولدوفي', 'nationality_en' => 'Moldovan', 'preferred_language' => 'ro'],
            ['code' => 'MC', 'country_ar' => 'موناكو', 'country_en' => 'Monaco', 'nationality_ar' => 'موناكي', 'nationality_en' => 'Monegasque', 'preferred_language' => 'fr'],
            ['code' => 'MN', 'country_ar' => 'منغوليا', 'country_en' => 'Mongolia', 'nationality_ar' => 'منغولي', 'nationality_en' => 'Mongolian', 'preferred_language' => 'mn'],
            ['code' => 'ME', 'country_ar' => 'الجبل الأسود', 'country_en' => 'Montenegro', 'nationality_ar' => 'مونتينيغري', 'nationality_en' => 'Montenegrin', 'preferred_language' => 'sr'],
            ['code' => 'MA', 'country_ar' => 'المغرب', 'country_en' => 'Morocco', 'nationality_ar' => 'مغربي', 'nationality_en' => 'Moroccan', 'preferred_language' => 'ar'],
            ['code' => 'MZ', 'country_ar' => 'موزمبيق', 'country_en' => 'Mozambique', 'nationality_ar' => 'موزمبيقي', 'nationality_en' => 'Mozambican', 'preferred_language' => 'pt'],
            ['code' => 'MM', 'country_ar' => 'ميانمار', 'country_en' => 'Myanmar', 'nationality_ar' => 'ميانماري', 'nationality_en' => 'Burmese', 'preferred_language' => 'my'],
            ['code' => 'NA', 'country_ar' => 'ناميبيا', 'country_en' => 'Namibia', 'nationality_ar' => 'ناميبي', 'nationality_en' => 'Namibian', 'preferred_language' => 'en'],
            ['code' => 'NR', 'country_ar' => 'ناورو', 'country_en' => 'Nauru', 'nationality_ar' => 'ناوروي', 'nationality_en' => 'Nauruan', 'preferred_language' => 'en'],
            ['code' => 'NP', 'country_ar' => 'نيبال', 'country_en' => 'Nepal', 'nationality_ar' => 'نيبالي', 'nationality_en' => 'Nepalese', 'preferred_language' => 'ne'],
            ['code' => 'NL', 'country_ar' => 'هولندا', 'country_en' => 'Netherlands', 'nationality_ar' => 'هولندي', 'nationality_en' => 'Dutch', 'preferred_language' => 'nl'],
            ['code' => 'NZ', 'country_ar' => 'نيوزيلندا', 'country_en' => 'New Zealand', 'nationality_ar' => 'نيوزيلندي', 'nationality_en' => 'New Zealander', 'preferred_language' => 'en'],
            ['code' => 'NI', 'country_ar' => 'نيكاراغوا', 'country_en' => 'Nicaragua', 'nationality_ar' => 'نيكاراغوي', 'nationality_en' => 'Nicaraguan', 'preferred_language' => 'es'],
            ['code' => 'NE', 'country_ar' => 'النيجر', 'country_en' => 'Niger', 'nationality_ar' => 'نيجري', 'nationality_en' => 'Nigerien', 'preferred_language' => 'fr'],
            ['code' => 'NG', 'country_ar' => 'نيجيريا', 'country_en' => 'Nigeria', 'nationality_ar' => 'نيجيري', 'nationality_en' => 'Nigerian', 'preferred_language' => 'en'],
            ['code' => 'KP', 'country_ar' => 'كوريا الشمالية', 'country_en' => 'North Korea', 'nationality_ar' => 'كوري شمالي', 'nationality_en' => 'North Korean', 'preferred_language' => 'ko'],
            ['code' => 'MK', 'country_ar' => 'مقدونيا الشمالية', 'country_en' => 'North Macedonia', 'nationality_ar' => 'مقدوني', 'nationality_en' => 'Macedonian', 'preferred_language' => 'mk'],
            ['code' => 'NO', 'country_ar' => 'النرويج', 'country_en' => 'Norway', 'nationality_ar' => 'نرويجي', 'nationality_en' => 'Norwegian', 'preferred_language' => 'no'],
            ['code' => 'OM', 'country_ar' => 'عمان', 'country_en' => 'Oman', 'nationality_ar' => 'عماني', 'nationality_en' => 'Omani', 'preferred_language' => 'ar'],
            ['code' => 'PK', 'country_ar' => 'باكستان', 'country_en' => 'Pakistan', 'nationality_ar' => 'باكستاني', 'nationality_en' => 'Pakistani', 'preferred_language' => 'ur'],
            ['code' => 'PW', 'country_ar' => 'بالاو', 'country_en' => 'Palau', 'nationality_ar' => 'بالاوي', 'nationality_en' => 'Palauan', 'preferred_language' => 'en'],
            ['code' => 'PS', 'country_ar' => 'فلسطين', 'country_en' => 'Palestine', 'nationality_ar' => 'فلسطيني', 'nationality_en' => 'Palestinian', 'preferred_language' => 'ar'],
            ['code' => 'PA', 'country_ar' => 'بنما', 'country_en' => 'Panama', 'nationality_ar' => 'بنمي', 'nationality_en' => 'Panamanian', 'preferred_language' => 'es'],
            ['code' => 'PG', 'country_ar' => 'بابوا غينيا الجديدة', 'country_en' => 'Papua New Guinea', 'nationality_ar' => 'بابوا غيني', 'nationality_en' => 'Papua New Guinean', 'preferred_language' => 'en'],
            ['code' => 'PY', 'country_ar' => 'باراغواي', 'country_en' => 'Paraguay', 'nationality_ar' => 'باراغواياني', 'nationality_en' => 'Paraguayan', 'preferred_language' => 'es'],
            ['code' => 'PE', 'country_ar' => 'بيرو', 'country_en' => 'Peru', 'nationality_ar' => 'بيروفي', 'nationality_en' => 'Peruvian', 'preferred_language' => 'es'],
            ['code' => 'PH', 'country_ar' => 'الفلبين', 'country_en' => 'Philippines', 'nationality_ar' => 'فلبيني', 'nationality_en' => 'Filipino', 'preferred_language' => 'fil'],
            ['code' => 'PL', 'country_ar' => 'بولندا', 'country_en' => 'Poland', 'nationality_ar' => 'بولندي', 'nationality_en' => 'Polish', 'preferred_language' => 'pl'],
            ['code' => 'PT', 'country_ar' => 'البرتغال', 'country_en' => 'Portugal', 'nationality_ar' => 'برتغالي', 'nationality_en' => 'Portuguese', 'preferred_language' => 'pt'],
            ['code' => 'QA', 'country_ar' => 'قطر', 'country_en' => 'Qatar', 'nationality_ar' => 'قطري', 'nationality_en' => 'Qatari', 'preferred_language' => 'ar'],
            ['code' => 'RO', 'country_ar' => 'رومانيا', 'country_en' => 'Romania', 'nationality_ar' => 'روماني', 'nationality_en' => 'Romanian', 'preferred_language' => 'ro'],
            ['code' => 'RU', 'country_ar' => 'روسيا', 'country_en' => 'Russia', 'nationality_ar' => 'روسي', 'nationality_en' => 'Russian', 'preferred_language' => 'ru'],
            ['code' => 'RW', 'country_ar' => 'رواندا', 'country_en' => 'Rwanda', 'nationality_ar' => 'رواندي', 'nationality_en' => 'Rwandan', 'preferred_language' => 'rw'],
            ['code' => 'KN', 'country_ar' => 'سانت كيتس ونيفيس', 'country_en' => 'Saint Kitts and Nevis', 'nationality_ar' => 'سانت كيتسي ونيفيسي', 'nationality_en' => 'Kittitian and Nevisian', 'preferred_language' => 'en'],
            ['code' => 'LC', 'country_ar' => 'سانت لوسيا', 'country_en' => 'Saint Lucia', 'nationality_ar' => 'سانت لوسي', 'nationality_en' => 'Saint Lucian', 'preferred_language' => 'en'],
            ['code' => 'VC', 'country_ar' => 'سانت فنسنت والغرينادين', 'country_en' => 'Saint Vincent and the Grenadines', 'nationality_ar' => 'سانت فنسنتي', 'nationality_en' => 'Vincentian', 'preferred_language' => 'en'],
            ['code' => 'WS', 'country_ar' => 'ساموا', 'country_en' => 'Samoa', 'nationality_ar' => 'ساموي', 'nationality_en' => 'Samoan', 'preferred_language' => 'sm'],
            ['code' => 'SM', 'country_ar' => 'سان مارينو', 'country_en' => 'San Marino', 'nationality_ar' => 'سان ماريني', 'nationality_en' => 'Sammarinese', 'preferred_language' => 'it'],
            ['code' => 'ST', 'country_ar' => 'ساو تومي وبرينسيب', 'country_en' => 'Sao Tome and Principe', 'nationality_ar' => 'ساوتومي', 'nationality_en' => 'Sao Tomean', 'preferred_language' => 'pt'],
            ['code' => 'SA', 'country_ar' => 'السعودية', 'country_en' => 'Saudi Arabia', 'nationality_ar' => 'سعودي', 'nationality_en' => 'Saudi', 'preferred_language' => 'ar'],
            ['code' => 'SN', 'country_ar' => 'السنغال', 'country_en' => 'Senegal', 'nationality_ar' => 'سنغالي', 'nationality_en' => 'Senegalese', 'preferred_language' => 'fr'],
            ['code' => 'RS', 'country_ar' => 'صربيا', 'country_en' => 'Serbia', 'nationality_ar' => 'صربي', 'nationality_en' => 'Serbian', 'preferred_language' => 'sr'],
            ['code' => 'SC', 'country_ar' => 'سيشل', 'country_en' => 'Seychelles', 'nationality_ar' => 'سيشيلي', 'nationality_en' => 'Seychellois', 'preferred_language' => 'en'],
            ['code' => 'SL', 'country_ar' => 'سيراليون', 'country_en' => 'Sierra Leone', 'nationality_ar' => 'سيراليوني', 'nationality_en' => 'Sierra Leonean', 'preferred_language' => 'en'],
            ['code' => 'SG', 'country_ar' => 'سنغافورة', 'country_en' => 'Singapore', 'nationality_ar' => 'سنغافوري', 'nationality_en' => 'Singaporean', 'preferred_language' => 'en'],
            ['code' => 'SK', 'country_ar' => 'سلوفاكيا', 'country_en' => 'Slovakia', 'nationality_ar' => 'سلوفاكي', 'nationality_en' => 'Slovak', 'preferred_language' => 'sk'],
            ['code' => 'SI', 'country_ar' => 'سلوفينيا', 'country_en' => 'Slovenia', 'nationality_ar' => 'سلوفيني', 'nationality_en' => 'Slovenian', 'preferred_language' => 'sl'],
            ['code' => 'SB', 'country_ar' => 'جزر سليمان', 'country_en' => 'Solomon Islands', 'nationality_ar' => 'سليماني', 'nationality_en' => 'Solomon Islander', 'preferred_language' => 'en'],
            ['code' => 'SO', 'country_ar' => 'الصومال', 'country_en' => 'Somalia', 'nationality_ar' => 'صومالي', 'nationality_en' => 'Somali', 'preferred_language' => 'so'],
            ['code' => 'ZA', 'country_ar' => 'جنوب أفريقيا', 'country_en' => 'South Africa', 'nationality_ar' => 'جنوب أفريقي', 'nationality_en' => 'South African', 'preferred_language' => 'en'],
            ['code' => 'KR', 'country_ar' => 'كوريا الجنوبية', 'country_en' => 'South Korea', 'nationality_ar' => 'كوري جنوبي', 'nationality_en' => 'South Korean', 'preferred_language' => 'ko'],
            ['code' => 'SS', 'country_ar' => 'جنوب السودان', 'country_en' => 'South Sudan', 'nationality_ar' => 'جنوب سوداني', 'nationality_en' => 'South Sudanese', 'preferred_language' => 'en'],
            ['code' => 'ES', 'country_ar' => 'إسبانيا', 'country_en' => 'Spain', 'nationality_ar' => 'إسباني', 'nationality_en' => 'Spanish', 'preferred_language' => 'es'],
            ['code' => 'LK', 'country_ar' => 'سريلانكا', 'country_en' => 'Sri Lanka', 'nationality_ar' => 'سريلانكي', 'nationality_en' => 'Sri Lankan', 'preferred_language' => 'si'],
            ['code' => 'SD', 'country_ar' => 'السودان', 'country_en' => 'Sudan', 'nationality_ar' => 'سوداني', 'nationality_en' => 'Sudanese', 'preferred_language' => 'ar'],
            ['code' => 'SR', 'country_ar' => 'سورينام', 'country_en' => 'Suriname', 'nationality_ar' => 'سورينامي', 'nationality_en' => 'Surinamese', 'preferred_language' => 'nl'],
            ['code' => 'SE', 'country_ar' => 'السويد', 'country_en' => 'Sweden', 'nationality_ar' => 'سويدي', 'nationality_en' => 'Swedish', 'preferred_language' => 'sv'],
            ['code' => 'CH', 'country_ar' => 'سويسرا', 'country_en' => 'Switzerland', 'nationality_ar' => 'سويسري', 'nationality_en' => 'Swiss', 'preferred_language' => 'de'],
            ['code' => 'SY', 'country_ar' => 'سوريا', 'country_en' => 'Syria', 'nationality_ar' => 'سوري', 'nationality_en' => 'Syrian', 'preferred_language' => 'ar'],
            ['code' => 'TJ', 'country_ar' => 'طاجيكستان', 'country_en' => 'Tajikistan', 'nationality_ar' => 'طاجيكستاني', 'nationality_en' => 'Tajikistani', 'preferred_language' => 'tg'],
            ['code' => 'TZ', 'country_ar' => 'تنزانيا', 'country_en' => 'Tanzania', 'nationality_ar' => 'تنزاني', 'nationality_en' => 'Tanzanian', 'preferred_language' => 'sw'],
            ['code' => 'TH', 'country_ar' => 'تايلاند', 'country_en' => 'Thailand', 'nationality_ar' => 'تايلاندي', 'nationality_en' => 'Thai', 'preferred_language' => 'th'],
            ['code' => 'TL', 'country_ar' => 'تيمور الشرقية', 'country_en' => 'Timor-Leste', 'nationality_ar' => 'تيموري', 'nationality_en' => 'Timorese', 'preferred_language' => 'pt'],
            ['code' => 'TG', 'country_ar' => 'توغو', 'country_en' => 'Togo', 'nationality_ar' => 'توغولي', 'nationality_en' => 'Togolese', 'preferred_language' => 'fr'],
            ['code' => 'TO', 'country_ar' => 'تونغا', 'country_en' => 'Tonga', 'nationality_ar' => 'تونغي', 'nationality_en' => 'Tongan', 'preferred_language' => 'to'],
            ['code' => 'TT', 'country_ar' => 'ترينيداد وتوباغو', 'country_en' => 'Trinidad and Tobago', 'nationality_ar' => 'ترينيدادي وتوباغوني', 'nationality_en' => 'Trinidadian and Tobagonian', 'preferred_language' => 'en'],
            ['code' => 'TN', 'country_ar' => 'تونس', 'country_en' => 'Tunisia', 'nationality_ar' => 'تونسي', 'nationality_en' => 'Tunisian', 'preferred_language' => 'ar'],
            ['code' => 'TR', 'country_ar' => 'تركيا', 'country_en' => 'Turkey', 'nationality_ar' => 'تركي', 'nationality_en' => 'Turkish', 'preferred_language' => 'tr'],
            ['code' => 'TM', 'country_ar' => 'تركمانستان', 'country_en' => 'Turkmenistan', 'nationality_ar' => 'تركماني', 'nationality_en' => 'Turkmen', 'preferred_language' => 'tk'],
            ['code' => 'TV', 'country_ar' => 'توفالو', 'country_en' => 'Tuvalu', 'nationality_ar' => 'توفالوي', 'nationality_en' => 'Tuvaluan', 'preferred_language' => 'en'],
            ['code' => 'UG', 'country_ar' => 'أوغندا', 'country_en' => 'Uganda', 'nationality_ar' => 'أوغندي', 'nationality_en' => 'Ugandan', 'preferred_language' => 'en'],
            ['code' => 'UA', 'country_ar' => 'أوكرانيا', 'country_en' => 'Ukraine', 'nationality_ar' => 'أوكراني', 'nationality_en' => 'Ukrainian', 'preferred_language' => 'uk'],
            ['code' => 'AE', 'country_ar' => 'الإمارات العربية المتحدة', 'country_en' => 'United Arab Emirates', 'nationality_ar' => 'إماراتي', 'nationality_en' => 'Emirati', 'preferred_language' => 'ar'],
            ['code' => 'GB', 'country_ar' => 'المملكة المتحدة', 'country_en' => 'United Kingdom', 'nationality_ar' => 'بريطاني', 'nationality_en' => 'British', 'preferred_language' => 'en'],
            ['code' => 'US', 'country_ar' => 'الولايات المتحدة', 'country_en' => 'United States', 'nationality_ar' => 'أمريكي', 'nationality_en' => 'American', 'preferred_language' => 'en'],
            ['code' => 'UY', 'country_ar' => 'أوروغواي', 'country_en' => 'Uruguay', 'nationality_ar' => 'أوروغواياني', 'nationality_en' => 'Uruguayan', 'preferred_language' => 'es'],
            ['code' => 'UZ', 'country_ar' => 'أوزبكستان', 'country_en' => 'Uzbekistan', 'nationality_ar' => 'أوزبكي', 'nationality_en' => 'Uzbekistani', 'preferred_language' => 'uz'],
            ['code' => 'VU', 'country_ar' => 'فانواتو', 'country_en' => 'Vanuatu', 'nationality_ar' => 'فانواتي', 'nationality_en' => 'Ni-Vanuatu', 'preferred_language' => 'bi'],
            ['code' => 'VA', 'country_ar' => 'الفاتيكان', 'country_en' => 'Vatican City', 'nationality_ar' => 'فاتيكاني', 'nationality_en' => 'Vatican', 'preferred_language' => 'it'],
            ['code' => 'VE', 'country_ar' => 'فنزويلا', 'country_en' => 'Venezuela', 'nationality_ar' => 'فنزويلي', 'nationality_en' => 'Venezuelan', 'preferred_language' => 'es'],
            ['code' => 'VN', 'country_ar' => 'فيتنام', 'country_en' => 'Vietnam', 'nationality_ar' => 'فيتنامي', 'nationality_en' => 'Vietnamese', 'preferred_language' => 'vi'],
            ['code' => 'YE', 'country_ar' => 'اليمن', 'country_en' => 'Yemen', 'nationality_ar' => 'يمني', 'nationality_en' => 'Yemeni', 'preferred_language' => 'ar'],
            ['code' => 'ZM', 'country_ar' => 'زامبيا', 'country_en' => 'Zambia', 'nationality_ar' => 'زامبي', 'nationality_en' => 'Zambian', 'preferred_language' => 'en'],
            ['code' => 'ZW', 'country_ar' => 'زيمبابوي', 'country_en' => 'Zimbabwe', 'nationality_ar' => 'زيمبابوي', 'nationality_en' => 'Zimbabwean', 'preferred_language' => 'en'],
        ];

        foreach ($rows as $row) {
            $data = [
                'nationality' => $row['nationality_ar'],
                'preferred_language' => $row['preferred_language'],
                'status' => 'active',
            ];

            if (Schema::hasColumn('nationalities', 'country_code')) {
                $data['country_code'] = $row['code'];
            }
            if (Schema::hasColumn('nationalities', 'country_name_ar')) {
                $data['country_name_ar'] = $row['country_ar'];
            }
            if (Schema::hasColumn('nationalities', 'country_name_en')) {
                $data['country_name_en'] = $row['country_en'];
            }
            if (Schema::hasColumn('nationalities', 'nationality_en')) {
                $data['nationality_en'] = $row['nationality_en'];
            }

            $unique = Schema::hasColumn('nationalities', 'country_code')
                ? ['country_code' => $row['code']]
                : ['nationality' => $row['nationality_ar']];

            Nationality::updateOrCreate($unique, $data);
        }
    }
}
